---
- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Don't run more than once an hour
        state: latest

  tasks:
    - name: Upgrade apt if needed
      apt:
        upgrade: 'yes'
        state: latest
    
    - name: See if reboot is needed for each host
      stat:
        path: /var/run/reboot-requried
      register: reboot_required_file

    - name: Skip reboot unless reboot-required file is present
      # This is a hack, since I really want a noop, to induce a notify
      command: echo hi
      notify: Reboot System
      when: reboot_required_file.stat.exists
      changed_when: false

  handlers:
    - name: Reboot System
      reboot:

...
