---
#  When this playlist completes, the nodes will be running "singleton"
#  kubernetes clusters, and must still be "joined" together into a
#  larger cluster.
- hosts: all
  become: yes

  tasks:  
    - name: Check to see if cgroup_memory is already enabled
      #  I could use the lookup('ansible.bulitin.csvfile', 'memory
      #  file=/proc/cgroups delimeter=" " col=4 default=0') ...but
      #  I'll just use a regex here.
      lineinfile:
        path: /proc/cgroups
        regex: '^memory\t.*\t1$'
        state: absent
        line: "If there would be a change, then cgroup_memory enabled"
      check_mode: yes
      register: mem_cgroup_present

    - name: Get the fact indicating location of cmdline.txt
      include_tasks:
        file: FindCmdLineTxtPath.yml
      when:
        - not mem_cgroup_present.changed

    - name: Read in cmdline.txt (to ensure we add options only once)
      command:
        cmd: "cat {{ cmdline_file_path }}"
      register: cmdline_contents
      changed_when: false
      when:
        - not mem_cgroup_present.changed

    - name: Augment cmdline.txt with options if necessary
      lineinfile:
        path: "{{ cmdline_file_path }}"
        regex: '^(.*)'
        line: '\1 {{ option }}'
        backrefs: true
      loop_control:
        loop_var: option
        label: "{{ option }}"
      loop:
        - cgroup_enable=memory
        - cgroup_memory=1
      when:
        - not mem_cgroup_present.changed
        - option not in cmdline_contents.stdout  # Avoid dups
      register: cmdline_file_edit

    - name: Reboot if boot option changed
      reboot:
      when:
        - cmdline_file_edit.changed

    - name: Validate cgroup_memory is now really set
      lineinfile:
        path: /proc/cgroups
        regex: '^memory\t.*\t1$'
        state: absent
      check_mode: yes
      when:
        - not mem_cgroup_present.changed
      register: mem_cgroup_finally_present

    - name: Assert that cgroup_memory was really found (enabled) now
      assert:
        that:
          - False
        fail_msg: >
          "Append to /boot/firmware/cmdline.txt the commands
          cgroup_enable=memory cgroup_memory=1"
      when:
        - not mem_cgroup_present.changed
        - not mem_cgroup_finally_present.changed

    - name: Ensure that snap is available
      # Note that some sites suggest "fuse" and "udev"
      # "udev" is already installed on both Raspian and Ubuntu
      # "fuse" is present on Raspian, but "fuse3" is used on Ubuntu
      apt:
        name: snapd
        state: present
      register: snapd_installation

    - name: Reboot if snapd was installed
      reboot:
        reboot_timeout: 90
      when:
        - snapd_installation.changed

    - name: Ensure snapd is running
      service:
        name: snapd
        state: started
        enabled: true
      register: snapd_running

    - name: Ensure presence of snap core
      snap:
        name: core
        state: present

    - name: Snap install of microk8s
      # If this fails with a timeout... just try again <sigh>
      # This is a documented (on web) problem with Ubuntu.
      # They are talking about raising the timeout limit in
      # snap, but they say it is hard to do :-/.
      # it will not timeout with Raspian.
      snap:
        name: microk8s
        classic: true
        state: present

    # To avoid needing to sudo for microk8s commands, we add this user
    # to the required group.
    - name: Add user to microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes
...
